# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: jwong-HelloWorld

package:
  exclude:
    - node_modules/**

plugins:
 - serverless-wsgi

provider:
  name: aws
  runtime: python2.7
  role: arn:aws:iam::646102706174:role/disco_dev_testillery_lambda
  deploymentBucket: us-west-2--mclass--serverless--${env:AWS_ACCOUNT}
  memorySize: 256
  region: us-west-2


functions:
  hello:
    handler: wsgi.handler
    events:
      - http:
          path: hello
          method: get

custom:
  wsgi:
    app: app.app