swagger: "2.0"

info:
  title: "Hello World API"
  version: "1.0"

paths:
  /hello/{name}:
    post:
      summary: Says hello to the username given in the path
      description: Generates a greeting message.
      operationId: app.post_greeting
      produces:
        - text/plain;
      responses:
        200:
          description: greeting response
          schema:
            type: string
          examples:
            "text/plain": "Hello John"
      parameters:
        - name: name
          in: path
          description: Name of the person to greet.
          required: true
          type: string
